-- ══════════════════════════════════════════════════════════════
-- 044_unified_intake_flow.sql
-- Unified Interview Flow: specialty_condition branching,
-- system_integrity node type, and integrity_report column
-- ══════════════════════════════════════════════════════════════

-- ─── 1. Add specialty_condition to prompt_sequence_nodes ─────
-- Enables per-node specialty routing in a single unified sequence
ALTER TABLE public.prompt_sequence_nodes
  ADD COLUMN IF NOT EXISTS specialty_condition TEXT;

-- Index for fast specialty filtering
CREATE INDEX IF NOT EXISTS idx_sequence_nodes_specialty
  ON public.prompt_sequence_nodes(specialty_condition)
  WHERE specialty_condition IS NOT NULL;

-- ─── 2. Extend node_type CHECK constraint ────────────────────
-- Add 'system_integrity' to the allowed node_type values
-- Drop old constraint and recreate with the new value
DO $$
BEGIN
  -- Drop the existing constraint if it exists
  IF EXISTS (
    SELECT 1 FROM information_schema.check_constraints
    WHERE constraint_name = 'prompt_sequence_nodes_node_type_check'
  ) THEN
    ALTER TABLE public.prompt_sequence_nodes
      DROP CONSTRAINT prompt_sequence_nodes_node_type_check;
  END IF;

  -- Re-create with system_integrity added
  ALTER TABLE public.prompt_sequence_nodes
    ADD CONSTRAINT prompt_sequence_nodes_node_type_check
    CHECK (node_type IN ('chat', 'system_gate', 'system_analysis', 'system_integrity'));
END $$;

-- ─── 3. Ensure intake_sessions table exists ──────────────────
-- This table was originally created via Supabase Studio; adding
-- the CREATE IF NOT EXISTS here as a safety net.
CREATE TABLE IF NOT EXISTS public.intake_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  patient_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  chief_complaint TEXT,
  specialty TEXT DEFAULT 'pending',
  status TEXT DEFAULT 'in_progress',
  snapshot JSONB,
  integrity_report JSONB,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- If table already exists, just add the integrity_report column
ALTER TABLE public.intake_sessions
  ADD COLUMN IF NOT EXISTS integrity_report JSONB;

-- Comment for documentation
COMMENT ON COLUMN public.intake_sessions.integrity_report IS
  'Chat integrity analysis: confidence score, fluidity metrics, per-section timing, red flags. Generated by system_integrity node.';

-- ══════════════════════════════════════════════════════════════
-- Done. No data migration needed — specialty_condition defaults
-- to NULL (global), integrity_report defaults to NULL.
-- ══════════════════════════════════════════════════════════════
